# -*- coding: utf-8 -*-
"""
Created on Mon Jul 1 14:34:30 2019

@author: Priyam
"""

mamamoo = 'https://open.spotify.com/artist/0XATRDCYuuGhk0oE7C0o5G'
hwasa = 'https://open.spotify.com/artist/7bmYpVgQub656uNTu6qGNQ'

redvelvet = 'https://open.spotify.com/artist/1z4g3DjTBBZKhvAroFlhOM'

exid = 'https://open.spotify.com/artist/1xs6WFotNQSXweo0GXrS0O'

missA = 'https://open.spotify.com/artist/1BEohdSWSBggmO979tzRwW'
sunmi = 'https://open.spotify.com/artist/6MoXcK2GyGg7FIyxPU5yW6'
yubin = 'https://open.spotify.com/artist/3JUj7c2h5xkdOf0GJ07VWE'
beg = 'https://open.spotify.com/artist/2GEPtT5RDxrmdi0A4mbDi7'
gain= 'https://open.spotify.com/artist/4R60A85t9mTZzCqJlVswuo'
secret = 'https://open.spotify.com/artist/503DjcVO5Ku1NgLPhVuNg7'
hyosung = 'https://open.spotify.com/artist/73RRzEpK7IQexOhC0CuTRZ'
jieun = 'https://open.spotify.com/artist/0D40an6y5Cv6sRzMGsRRQ8'
gidle = 'https://open.spotify.com/artist/2AfmfGFbe0A0WsTYm0SDTx'

loona = 'https://open.spotify.com/artist/52zMTJCKluDlFwMQWmccY7'
loona_yyxy = 'https://open.spotify.com/artist/4JKDJj0bOTw07GrQ9pmcUS'
lonna_oddeyecircle = 'https://open.spotify.com/artist/5KPaeBm0fVfCSZLydp9jdy'
wjsn = 'https://open.spotify.com/artist/6hhqsQZhtp9hfaZhSd0VSD'
jimin = 'https://open.spotify.com/artist/2YXlVLKq3X3soXd2aXUtIT'
gugudan = 'https://open.spotify.com/artist/0h7XZWgoxlY49uSUj7MVRY'
fromis_9 = 'https://open.spotify.com/artist/24nUVBIlCGi4twz4nYxJum'
ohmygirl = 'https://open.spotify.com/artist/2019zR22qK2RBvCqtudBaI'
pristin = 'https://open.spotify.com/artist/6VAphrHp0Oc88qg9BDaH9D'
k_da = 'https://open.spotify.com/artist/4gOc8TsQed9eqnqJct2c5v'
weki_meki = 'https://open.spotify.com/artist/5LWkv2hDbDwZL3zNwZYNPx'
ioi = 'https://open.spotify.com/artist/6RKnXXyprPjhBdCvL802Ku'
momoland = 'https://open.spotify.com/artist/5RR0MLwcjc87wjSw2JYdwx'
blackpink = 'https://open.spotify.com/artist/41MozSoPIsD1dJM0CLPjZF'
twice = 'https://open.spotify.com/artist/7n2Ycct7Beij7Dj7meI4X0'
taeyeon = 'https://open.spotify.com/artist/3qNVuliS40BLgXGxhdBdqu'
tts = 'https://open.spotify.com/artist/7AKHnZVqwXYuUwWJ8UGL5q'
tiffany = 'https://open.spotify.com/artist/2lkCfFklQDBPlQzS4tR3VP'
chungha = 'https://open.spotify.com/artist/2PSJ6YriU7JsFucxACpU7Y'
kard = 'https://open.spotify.com/artist/2JhAlkmukNvarUpGhTFXUQ'
bolbbalgan4 = 'https://open.spotify.com/artist/4k5fFEYgkWYrYvtOK3zVBl'
aoa = 'https://open.spotify.com/artist/54gWVQFHf8IIqbjxAoOarN'
girlsday = 'https://open.spotify.com/artist/13kJgvU22LHMsJtGWLmx7W'
stellar = 'https://open.spotify.com/artist/1rTwKjYcA7diHAD2c8ZozT'
apink = 'https://open.spotify.com/artist/2uWcrwgWmZcQc3IPBs3tfU'
brave_girls = 'https://open.spotify.com/artist/5F47QnV4fjYwl0u5GaSDEx'
after_school = 'https://open.spotify.com/artist/1loWI8jVk9btgJXHgqHXPD'
orange_caramel = 'https://open.spotify.com/artist/2QHTtUsN6Q13w3QHdfRqsK'
sistar = 'https://open.spotify.com/artist/2wTLheTmMcFCA4hdY8hZJP'
sistar_19 = 'https://open.spotify.com/artist/5Q0U6ogBrMX2oxmxy5OTzU'
rania = 'https://open.spotify.com/artist/5sUKi0QlHVxvsCzmrhJsFO'
nine_muses = 'https://open.spotify.com/artist/55tJwpPIz9BMrSLM45iEXX'
hellovenus = 'https://open.spotify.com/artist/3TW9U1f93tpGBsEtCSf7JG'
bestie = 'https://open.spotify.com/artist/1HiZjIv6iLp9cs5vX0AJKo'
fx = 'https://open.spotify.com/artist/3wRA5UYoo08BBKJnzyKkpF'
crayon_pop = 'https://open.spotify.com/artist/0ODX6aegsZkBmBeMA5qqwi'
ailee = 'https://open.spotify.com/artist/3uGFTJ7JMllvhgGpumieHF'
spica = 'https://open.spotify.com/artist/5lvNsrcLos9vZpLQCJk4YK'
t_ara = 'https://open.spotify.com/artist/1R52cwGf75yTf7I3Q0Irf8'
four_minute = 'https://open.spotify.com/artist/6cdC1cwqh3eJAXaxXJt2jv'
two_ne1 = 'https://open.spotify.com/artist/1l0mKo96Jh9HVYONcRl3Yp'
kara = 'https://open.spotify.com/artist/7aZ221EQfonNG2lO9Hh192'
wonder_girls = 'https://open.spotify.com/artist/3Cv2vi3WTl8VZOTdrBkKdM'
snsd = 'https://open.spotify.com/artist/0Sadg1vgvaPqGTOjxu0N6c'
dalshabet = 'https://open.spotify.com/artist/10xsuRNvidaOLxWd3fRIel'
fiestar = 'https://open.spotify.com/artist/3IVjXrnR0npv1LY24kQSzd'
g_na = 'https://open.spotify.com/artist/3hzcooxMtbApMTvvn6XKVA'
clc = 'https://open.spotify.com/artist/6QyO41KctzGc70mVaVnXQO'
lee_hi = 'https://open.spotify.com/artist/7cVZApDoQZpS447nHTsNqu'
heize = 'https://open.spotify.com/artist/5dCvSnVduaFleCnyy98JMo'
akmu = 'https://open.spotify.com/artist/6OwKE9Ez6ALxpTaKcT5ayv'
melody_day = 'https://open.spotify.com/artist/7lD3HWDgSgMxHNFno02dJp'
sonamoo = 'https://open.spotify.com/artist/2MY1GcYSTw3QH2C1Umzsq0'
berrygood = 'https://open.spotify.com/artist/2gW6OQobWMbkR1cKo72H2t'

zion_t='https://open.spotify.com/artist/5HenzRvMtSrgtvU16XAoby'
bigbang = 'https://open.spotify.com/artist/4Kxlr1PRlDKEB0ekOCyHgX'
jay_park ='https://open.spotify.com/artist/4XDi67ZENZcbfKnvMnTYsI'
g_dragon = 'https://open.spotify.com/artist/30b9WulBM8sFuBo17nNq9c'
top = 'https://open.spotify.com/artist/4rO1Cxt1NcUcX2XbF19rDI'
vixx = 'https://open.spotify.com/artist/5BkB3rXc0qIdUtuEnhbK0A'
btob = 'https://open.spotify.com/artist/2hcsKca6hCfFMwwdbFvenJ'
nuest = 'https://open.spotify.com/artist/1iQfn1B8V25iQoolQakyAZ'
b1a4 = 'https://open.spotify.com/artist/3sxWOFw4MSN54SIQ8np6iG'
teen_top = 'https://open.spotify.com/artist/3offPqpKAKmpQkIdWnjzkc'
winner = 'https://open.spotify.com/artist/5DuzBeOgFwViFcv00Q5PFb'
epik_high = 'https://open.spotify.com/artist/5snNHNlYT2UrtZo5HCJkiw'
eric_nam = 'https://open.spotify.com/artist/2FLqlgckDKdmpBrvLAT5BM'
seventeen = 'https://open.spotify.com/artist/7nqOGRxlXj7N2JYbgNEjYH'
nct = 'https://open.spotify.com/artist/48eO052eSDcn8aTxiv6QaG'
nct_u = 'https://open.spotify.com/artist/3paGCCtX1Xr4Gx53mSeZuQ'
nct_127 = 'https://open.spotify.com/artist/7f4ignuCJhLXfZ9giKT7rH'
nct_dream = 'https://open.spotify.com/artist/1gBUSTR3TyDdTVFIaQnc02'
stray_kids = 'https://open.spotify.com/artist/2dIgFjalVxs4ThymZ67YCE'
got7 = 'https://open.spotify.com/artist/6nfDaffa50mKtEOwR8g4df'
monsta_x = 'https://open.spotify.com/artist/4TnGh5PKbSjpYqpIdlW5nz'
two_am = 'https://open.spotify.com/artist/5SnaL8SsjGMHQNyqpa8Zos'
two_pm = 'https://open.spotify.com/artist/5iRPbkcPmqAFFwDUj6ywVS'
super_junior = 'https://open.spotify.com/artist/6gzXCdfYfFe5XKhPKkYqxV'
mblaq = 'https://open.spotify.com/artist/14f1WN9TUDVBK4sHUStmLG'
tvxq = 'https://open.spotify.com/artist/6nVMMEywS5Y4tsHPKx1nIo'
ftisland = 'https://open.spotify.com/artist/6KhH771vq2X2Aom91nNzpZ'
shinee = 'https://open.spotify.com/artist/2hRQKC0gqlZGPrmUKbcchR'
cnblue = 'https://open.spotify.com/artist/6dCz3spfpIvqqqsIoP6wXi'
u_kiss = 'https://open.spotify.com/artist/2GB76Lm833jVI5kLvKEB7Z'
beast = 'https://open.spotify.com/artist/1Pr9gT0veB2tgcisQeIGoC'
shinhwa = 'https://open.spotify.com/artist/0jVvkFPa6YbFXQ3Qmhita0'
se7en = 'https://open.spotify.com/artist/14yLuCwlBqteUdBqx9soJV'

top3 = [mamamoo,redvelvet,exid]

artists = [mamamoo,hwasa,redvelvet,exid,secret,missA,sunmi,yubin,beg,gain,hyosung,jieun,gidle,loona,loona_yyxy,lonna_oddeyecircle,wjsn,jimin,gugudan,fromis_9,ohmygirl,pristin,k_da,weki_meki,ioi,momoland,blackpink,twice,taeyeon,tts,tiffany,chungha,kard,bolbbalgan4,aoa,girlsday,stellar,apink,brave_girls,after_school,orange_caramel,sistar,sistar_19,rania,nine_muses,hellovenus,bestie,fx,crayon_pop,ailee,spica,t_ara,four_minute,two_ne1,kara,wonder_girls,snsd,dalshabet,fiestar,g_na,clc,lee_hi,heize,akmu,melody_day,sonamoo,berrygood,zion_t,bigbang,jay_park,g_dragon,top,vixx,btob,nuest,b1a4,teen_top,winner,epik_high,eric_nam,seventeen,nct,nct_u,nct_127,nct_dream,stray_kids,got7,monsta_x,two_am,two_pm,super_junior,mblaq,tvxq,ftisland,shinee,cnblue,u_kiss,beast,shinhwa,se7en
           ]

sans_missA = [mamamoo,hwasa,redvelvet,exid,secret,sunmi,yubin,beg,gain,hyosung,jieun,gidle,loona,loona_yyxy,lonna_oddeyecircle,wjsn,jimin,gugudan,fromis_9,ohmygirl,pristin,k_da,weki_meki,ioi,momoland,blackpink,twice,taeyeon,tts,tiffany,chungha,kard,bolbbalgan4,aoa,girlsday,stellar,apink,brave_girls,after_school,orange_caramel,sistar,sistar_19,rania,nine_muses,hellovenus,bestie,fx,crayon_pop,ailee,spica,t_ara,four_minute,two_ne1,kara,wonder_girls,snsd,dalshabet,fiestar,g_na,clc,lee_hi,heize,akmu,melody_day,sonamoo,berrygood,zion_t,bigbang,jay_park,g_dragon,top,vixx,btob,nuest,b1a4,teen_top,winner,epik_high,eric_nam,seventeen,nct,nct_u,nct_127,nct_dream,stray_kids,got7,monsta_x,two_am,two_pm,super_junior,mblaq,tvxq,ftisland,shinee,cnblue,u_kiss,beast,shinhwa,se7en
           ]

test_set = [mamamoo,redvelvet,exid,girlsday,sistar,stellar,four_minute,after_school,bestie,loona,gidle,sunmi,ohmygirl,pristin,apink,spica,aoa,ioi,chungha,momoland,wjsn,orange_caramel,fiestar,dalshabet,snsd]
